---

- name: Apply Oratab
  template:
    src: oratab.j2
    dest: /etc/oratab
    owner: root
    group: root
    mode: 0644
  when: oracle_client_set_oratab

- name: Make sure Network Admin folder exists
  file:
    path: "{{ oracle_client_oracle_home }}/network/admin"
    state: directory
    owner: "{{ __oracle_client_user }}"
    group: "{{ __oracle_client_group }}"
  when: oracle_client_set_tnsnames

- name: Implement tnsnames.ora
  template:
    src: tnsnames.ora.j2
    dest: "{{ oracle_client_oracle_home }}/network/admin/tnsnames.ora"
    owner: "{{ __oracle_client_user }}"
    group: "{{ __oracle_client_group }}"
    mode: 0644
  when: oracle_client_set_tnsnames

- name: Set Oracle Client Environmental Variables
  template:
    src: oracle-client.sh.j2
    dest: "/etc/profile.d/{{oracle_client_environment_shell_name}}"
    owner: root
    group: root
    mode: 0644
  when: oracle_client_set_environmental_variables

- name: Check If Precompiler Installed
  stat:
    path: "{{ oracle_client_oracle_home }}/precomp/admin/pcscfg.cfg"
  register: __oracle_client_precompiler

- name: Check For Location of GCC Libraries for Precompiler
  command: find /usr/lib/gcc -wholename "*/include"
  changed_when: false
  register: __oracle_client_gcc_libraries
  when: __oracle_client_precompiler.stat.exists

- name: Apply PreCompiler C Template
  template:
    src: pcscfg.cfg.j2
    dest: "{{ oracle_client_oracle_home }}/precomp/admin/pcscfg.cfg"
  when: __oracle_client_precompiler.stat.exists
